### ISSUE TITLE
What makes it to the newest pool? 

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#10]
I notice questions from April together with the ones last added and they stretch on 5 pages. Shouldn't we refer to the last month perhaps only?

**Comment by lucianferoiu** [comment]
For the moment there is no separate _pool_ - I simply order them by date; so basically _Popular_ and _Newest_ return all the questions, the only difference is the order (by votes count and publication date respectively). Think of them not as separate sets but sorting orders...

This we can change, of course, and limit the _Newest_ to only the most recent 25 or this month's questions - but for now it is all arbitrary and I don't know which criterion will be the most suitable; we don't know how many questions we will have, how often we will publish new ones, etc.

**Comment by litebluecheese** [comment]
You're perfectly right still... Could you put in the newest the last month's? Just to give an idea of what could be there. I'm just thinking about the marketing now.

**Comment by lucianferoiu** [comment]
Alright.. But beware that the fake data currently in the _TEST_ environment will probably not show anything in that case :)

Let's clarify: _last month_ means 1) within the current calendar month or 2) today - 30 days ?

**Comment by litebluecheese** [comment]
30 days
