### ISSUE TITLE
Published question: title should not be editable after question has been published

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#12]
I think we've discussed about this but it's not in github. I'm not sure about the details of a published question, if we should allow to change in order to add further 'evidence', BUT the title should not be editable, for sure. Otherwise people end up answering different questions.

**Comment by lucianferoiu** [comment]
Oh, so you'd suggest allowing changes in everything but the title.. Mkay...

**Comment by litebluecheese** [comment]
Not sure. Sincerely, I would not allow changes. On the other hand it may be useful to add to the 'debate' new information when this exists. Ideally there could be a second textbox only for updates, that will spit the info at the end of the question details, with the date of the update. They do it in newspaper articles as well. However, you might accuse me of building nuclear plants again so if I have to choose between updates or not... I don't know what to choose. :D

**Comment by lucianferoiu** [comment]
Yeah, this sounds like an after-launch enhancement... Are you familiar with the MVP(https://en.wikipedia.org/wiki/Minimum_viable_product) concept? I'm a die-hard of that approach...

**Comment by litebluecheese** [comment]
You're right. For now things could be black or white. So, NO changes allowed. Not in the title, nor in the text. I think this is the politically safe stance.

**Comment by lucianferoiu** [comment]
If we won't do anything about it, maybe we should close it..

**Comment by litebluecheese** [comment]
Right now it can be edited after publishing, so it shouldnt be editable.

**Comment by lucianferoiu** [comment]
sorry, my bad...

**Comment by lucianferoiu** [comment]
The title is not editable anymore..
