### ISSUE TITLE
Small enhancement: add closing buttons on translations tabs

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#13]
![screen shot 2015-08-03 at 14 00 31](https://cloud.githubusercontent.com/assets/13371295/9059514/5feff928-3ab3-11e5-87d7-69d2a1021eaa.png)

**Comment by lucianferoiu** [comment]
Alright... But just so you know, if you were worried that the tab bar will get overcrowded if you open too many translations, it won't: only the last 5 tabs + English are kept around (FIFO)

**Comment by litebluecheese** [comment]
Ok, but this is unexpected behaviour for a window with tabs.
