### ISSUE TITLE
Percents mismatch between backend and front end for an archived question.

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#14]
Q0353: Accusamus in ut reiciendis numquam autem dolorum? 
Recently archived. Introduced institutional vote results:

![screen shot 2015-08-04 at 14 39 08](https://cloud.githubusercontent.com/assets/13371295/9059987/f91ebb4e-3ab7-11e5-89bc-85777a03f443.png)

In the front end, the percent of yes sayers in the EP is 55%, instead of 56%:

![screen shot 2015-08-04 at 14 39 25](https://cloud.githubusercontent.com/assets/13371295/9060011/25e209ce-3ab8-11e5-9a7d-f020933d992f.png)

The fault of the lovely bars? A round up thingie?

**Comment by lucianferoiu** [comment]
It's only 1% off so it can either be a rounding issue or a deeper problem. Either way, I'll check :)

**Comment by litebluecheese** [comment]
Yes, that 1% made me suspect a rounding problem too. 

If I may add a minor design enhancement here... Could you pls make the YES in the citizens vote result green instead of red?

![screen shot 2015-08-04 at 15 07 28](https://cloud.githubusercontent.com/assets/13371295/9060251/b67a6330-3aba-11e5-8da6-93d543dc3815.png)

**Comment by lucianferoiu** [comment]
Sure - I'll use the darker shade of teal for better contrast... 
Just as well, I should remove the shadow of the YES/NO etc. in the institutional results... it's ugly.. Should I keep the text black or should I make it cherry-red?

**Comment by litebluecheese** [comment]
I think it could have the same design as in the citizens' position. The more unitary the design the easiest to follow the numbers/results...

**Comment by lucianferoiu** [comment]
Oh, you mean the black text on coloured background? Damn, why didn't I think of that?! And if you'd knew how much I fought with myself to not mention "consistency" to your proposition earlier, and all this time I was the one breaking the uniformity :) You got me, fair and square.. All that remains to be said is: roger wilco :D

**Comment by litebluecheese** [comment]
Yes, the black text on coloured background. :-) What was the consistency for?

**Comment by lucianferoiu** [comment]
:) well, your proposition for teal "Yes" - everywhere else (but mainly the front-page), the Yes/No  (without percentages, just values) are cherry-red on white or white on cherry-red...
But let's give this teal version a go...

**Comment by lucianferoiu** [comment]
We basically should try a bunch of combinations and see what sticks - and then run a "consistency" rehash over the entire design...

**Comment by litebluecheese** [comment]
Well, the results display its kinda different than the voting buttons - if thats where inconsistency is.
At least for displaying results I would stick to yes green, no red... its visible, clear..  but we can also apply that to voting buttons if you wish.

**Comment by lucianferoiu** [comment]
No, I think the voting buttons should stay within the current lines, for a couple of reasons:
- green will look ugly inside the red question overlay (in the main page)
- would influence voting: green=good, red=bad

**Comment by litebluecheese** [comment]
Ok, but then perhaps we should get rid of the red and use another colour combination strictly for the buttons: grey/black/white/prussian blue :-) kiddin' with the blue. Would be nice to have a meetup at some point to discuss strictly the design.

**Comment by lucianferoiu** [comment]
Fixed - except for the teal YES on citizens/official votes in the question details.. It looks better in the current way (let's not abuse the colours too much)

**Comment by litebluecheese** [comment]
I had in mind more the consistency and symbolistic than the looks... if we display everywhere (except buttons) yes on green and no on red. But ok, it's not so important really.
