### ISSUE TITLE
Do we allow further modification of the archival data after it has been completed?

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#15]
Once the percentages are in there should they still be modified? One can make a mistake and introduce the wrong percentage, but this editing freedom could also create a breach allowing evil intentioned folks to comb a bit the data at a later moment in time...

**Comment by lucianferoiu** [comment]
People allowed to archive/edit archived questions is limited.
We don't have the access rights in place yet but basically that's a small risk...

**Comment by lucianferoiu** [comment]
I will close this issue since it's about access rights and is just a side-effect of issue #5...
