### ISSUE TITLE
Piechart in the details/voting section?

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#16]
I see you've added it to the archived section but not in the details one. Is there a reason behind it?

**Comment by lucianferoiu** [comment]
Yes - it's not its place in the published questions details...

**Comment by litebluecheese** [comment]
Why?

**Comment by lucianferoiu** [comment]
Where do you want it?

**Comment by litebluecheese** [comment]
Tell me why you don't think it is its place there. maybe you're right. :D

**Comment by litebluecheese** [comment]
![corgi meme](https://cloud.githubusercontent.com/assets/13371295/9066166/b500db78-3ade-11e5-8c2e-6d9ac46dec52.jpeg)

**Comment by lucianferoiu** [comment]
![image](https://cloud.githubusercontent.com/assets/39299/9066267/41ca857c-3adf-11e5-8ed6-b00e4922691b.png)

**Comment by litebluecheese** [comment]
Fun is over. I'm going to the movies... :D

**Comment by lucianferoiu** [comment]
I'm already there! :)
