### ISSUE TITLE
I can still change title and content of an archived question...

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#2]
This shouldn't be possible for a published or archived question. For a published question, perhaps we can allow additional content to be appended, provide new proof of evidence had been found etc Also date of archival does not appear for last archived question (0337).

**Comment by litebluecheese** [comment]
We have to implement a workflow logic for the questions.

**Comment by lucianferoiu** [comment]
"We have to implement a workflow logic for the questions." - the Commission would be so proud :)

Our workflow is pretty straightforward: proposed->published->archived (and at any point it can be deleted). A more elaborate workflow would be overkill...

**Comment by litebluecheese** [comment]
Well, the idea is not to implement it for the sake of implementation but because it makes sense. When I open a question I don't know what status it is in (unless I remember I took it from the bunch of published/archived etc) All tabs are active as if one can change anything, anywhere at anytime. Take a proposed question, I can play around archival data, although this makes little sense...  This doesn't have to be implemented now, but sometimes it will have to be done.

**Comment by lucianferoiu** [comment]
OK. Created a new issue #6 to deal with this particular issue (as this one referred to a bug).
