### ISSUE TITLE
Asking for translators

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#21]
I see that you display the English version (original) when no translation is available for a question, which is good. But do you think we could display a small message (in English or their language?) in a page containing untranslated questions telling the users that we apologize for the untranslated questions and asking them if they could help us by becoming a translator for the platform? In order to speed up the process of finding translators... or otherwise to use google translate... :D Or this is not in the MVP. :-)

**Comment by lucianferoiu** [comment]
Where (when) do you want to display this notification? In the main page if any one of the questions are not translated? In the question details?

**Comment by litebluecheese** [comment]
The main page will do I believe. Would be cool to make it look like a sticky note (which can be closed). :-)

**Comment by lucianferoiu** [comment]
Alright... 

Minor point: The only concern I have here is how it will influence a first-impression of a new visitor: if we assault him/her with this message before (s)he even comprehended what's in front of him/her... we might loose a _customer_

**Comment by litebluecheese** [comment]
And if he chooses Italian and everything on the page is in English, what would be his reaction? :-/

**Comment by lucianferoiu** [comment]
_everything_ <- I hope that by the time of the launch the untranslated elements will be the exception and not the rule...

**Comment by lucianferoiu** [comment]
..with the exception of Gaelic for which I remember there are very few translators in the world, even at the Commission

**Comment by litebluecheese** [comment]
Yeah, Gaelic an Suomi... wtf...

**Comment by lucianferoiu** [comment]
Suomi is Finnish :)

**Comment by litebluecheese** [comment]
Yeah, sorry, thought it was the language of the lapps... sami whatever :-)

**Comment by litebluecheese** [comment]
i remember that one is also on the official list of languages but perhaps i'm wrong.

**Comment by lucianferoiu** [comment]
go to http://ec.europa.eu/ to see the official ones

**Comment by litebluecheese** [comment]
Yeah, not in there. Lapland language is Saami. Perhaps Suomi is a variation of that, or viceversa. :-)

**Comment by lucianferoiu** [comment]
An alert asking for help with translations is displayed in the main page:
- if the current language is not English (for obvious reasons)
- if there is at least one question has any of the title or description not translated in the current language
- the alert is shown only once a day so we don't annoy the visitors (so pay attention when checking if it works - you may delete the YV4EUMSG01 cookie to reset the timer)

**Comment by litebluecheese** [comment]
can i flag an issue for later verification? :D

**Comment by lucianferoiu** [comment]
:) dunno - you can add a reminder on your phone (best obvious alternative)
