### ISSUE TITLE
Can't choose Romanian and a few other languages in the languages dropdown

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#22]
This is where the languages list finishes in my browser on my resolution:

![screen shot 2015-08-07 at 15 12 33](https://cloud.githubusercontent.com/assets/13371295/9135508/e30d27b2-3d16-11e5-864c-04cac09e77bc.png)

**Comment by lucianferoiu** [comment]
Yeah, bummer... I'll try to find an elegant solution (either scrollable menu or sub-menu).

**Comment by litebluecheese** [comment]
Sub-menu? How could that be?

**Comment by lucianferoiu** [comment]
Dunno, haven't really thought about it - it's not some off-the-shelf solution I can apply, I'll have to tweak something...

**Comment by litebluecheese** [comment]
I know. We should group them according to origins... :D

**Comment by litebluecheese** [comment]
Or open a map to choose ur language... :-)

**Comment by lucianferoiu** [comment]
Maps and flags are not a good idea to represent languages.
I know you have to be pulling my leg with the _group by origin_ solution :)

Probably I will find a way to make the menu scrollable.

**Comment by litebluecheese** [comment]
Of course I do... :D However it would be very original... :-))))))))

**Comment by litebluecheese** [comment]
Make it a list box.

**Comment by lucianferoiu** [comment]
Aaand isn't that a menu with a scroll, except ... ugly? :D

**Comment by litebluecheese** [comment]
yeah, it has a scroll and it can be css-ed to something decent i believe.

**Comment by lucianferoiu** [comment]
The language menu is now scrollable so all languages can fit in a smaller area
_NB: This is not a combo-box, as suggested before, but close_
