### ISSUE TITLE
An editor should be able to mark a translation as verified/final.  

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#4]
In this status, the translation cannot be changed anymore. This would prevent an accidental change right before publishing, for example.

**Comment by lucianferoiu** [comment]
![image](https://cloud.githubusercontent.com/assets/39299/8820966/7bf35ca6-3062-11e5-94f6-da5f2a4287ee.png)

**Comment by litebluecheese** [comment]
Uhhh, this was there and I did not see it? Or you've just added it?

**Comment by lucianferoiu** [comment]
Just added it this morning :p

**Comment by litebluecheese** [comment]
You're fantastic! :-) And yeah, I know what we write here is public info... :D

**Comment by lucianferoiu** [comment]
Oh, you're so skilled in playing me like a fiddle :P
