### ISSUE TITLE
Number of (tagged) questions in the dropdown menu mismatches number of questions displayed.

### ISSUE THREAD

**Issue by litebluecheese** [lucianferoiu/youvote4eu#7]
Check for example #environment: 7 questions in the drop-down menu, but only 6 displayed.

**Comment by lucianferoiu** [comment]
![issue_7](https://cloud.githubusercontent.com/assets/39299/9054964/e7a6c45c-3a8e-11e5-9d7e-1651f530e830.png)

Again a result of the fake data... basically I had the tag attached more than once to a question.

All these fake data bugs (that aren't really bugs) really makes me look like a worse developer than I am :(

**Comment by litebluecheese** [comment]
Oh, dear, no worries... these are 'finesse' issues, not even bugs, as you say. I'm even frustrated by the small number of bugs I found in your work. ;-)

**Comment by lucianferoiu** [comment]
..that's 'cause you're not trying hard enough :p

**Comment by litebluecheese** [comment]
I'm not done yet.
